### PR TITLE
Changes so far from the MAPcore team

### PR DESCRIPTION
**Pull request by alan-wu**
# Description

Initial commit for MAPcore, it includes npm build script and few static files. Also includes changes that enable navigation onto the MAPpage.

## Type of change

Delete those that don't apply.
- [ ] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Built and deployed successfully on Herokuapp https://abi-test-portal.herokuapp.com/
It is displaying an empty windows as the data is not yet available.

### CODE REVIEW

**Comment by jwagenaar** [comment]
Alan, can you provide instructions how to build and run from scratch locally? Currently, this branch does not build (missing pathlib, ContextDecorator, )

**Comment by dbrnz** [comment]
@jwagenaar what version of Python are you running??

**Comment by jwagenaar** [comment]
Hi David, the portal is deployed using Python 2.7. 
Did you implement this using Python 3?

**Comment by dbrnz** [comment]
Yes, Python 3. Python 2.7 has just over 5 months of life left, before it becomes unsupported...

I am however just finishing of code changes so that flatmap content is retrieved from a separate map server, meaning that the flatmap-related Python 3 code in `views.py` will disappear. There should be a PR with these changes sometime in the next 24 hours.

**Comment by alan-wu** [comment]
Hi Joost, the build process should be the same as before:

`pip install -r requirements`
`npm build heroku-postbuild`

It was tested on our own heroku instance.

By the way, I thought the default python version on heroku is pytho3.6?

**Comment by jwagenaar** [comment]
Okay,
Yep, that makes sense. I'll have a second look at it and merge if I can get
it to work later today.
Looks pretty awesome on your instance though! Exciting to see everything
fall into place.

Joost

______________________

Joost Wagenaar, Ph.D. | VP, Scientific Applications | Blackfynn Inc.

joost@blackfynn.com | Phone:  (412) 726-9859

**Pull request merged**
